name: drinky
version: 0.0.3+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  flutter_launcher_icons: 0.13.1
  url_launcher: 6.1.14
  provider: 6.0.5
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#  run following command to change the icon -> $ flutter pub pub run flutter_launcher_icons:main
flutter_icons:
   image_path: "assets/images/iconv2.png"
   android: true
   ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo-christmas.png
    - assets/images/bg-menu.png
    - assets/images/bg-home.png
    - assets/images/bg-home-christmas.png
    - assets/images/sad.jpg
    - assets/drink_codes.json
    - assets/ingredient_codes.json
    - assets/images/bottles/
    - assets/images/drinks/